version: '3.6'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - "wilfly"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  wilfly:
    build: 
      context: .
    ports:
      - "8080:8080"
      - "51331:51331"
      - "51016:51016"
    depends_on:
      - "postgres"
    restart: always
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data:
